import type { NestExpressApplication } from "@nestjs/platform-express";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";

/** Mounts Swagger UI at /docs. Returns false (and mounts nothing) unless explicitly enabled. */
export function configureOpenApi(app: NestExpressApplication, enabled: boolean): boolean {
  if (!enabled) {
    return false;
  }

  const documentConfig = new DocumentBuilder()
    .setTitle("Sketchblock Collab Server API")
    .setDescription("HTTP API for server-side collaboration session management. Socket.IO realtime events are documented separately.")
    .setVersion("0.1.0")
    .addBearerAuth(
      {
        type: "http",
        scheme: "bearer",
        bearerFormat: "collab-ticket",
        description: "Short-lived signed collab ticket generated by apps/web.",
      },
      "collab-ticket",
    )
    .addTag("Health")
    .addTag("Sessions")
    .build();

  const document = SwaggerModule.createDocument(app, documentConfig);
  SwaggerModule.setup("docs", app, document, {
    swaggerOptions: {
      persistAuthorization: true,
      tagsSorter: "alpha",
    },
  });
  return true;
}
